// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: healthcheck/api.proto

package healthcheck

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HealthCheckerClient is the client API for HealthChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthCheckerClient interface {
	//HTTP(S) health check
	HttpCheck(ctx context.Context, in *HttpCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	//ICMP health check
	IcmpCheck(ctx context.Context, in *IcmpCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	//TCP health check
	TcpCheck(ctx context.Context, in *TcpCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type healthCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthCheckerClient(cc grpc.ClientConnInterface) HealthCheckerClient {
	return &healthCheckerClient{cc}
}

func (c *healthCheckerClient) HttpCheck(ctx context.Context, in *HttpCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/healthcheck.HealthChecker/HttpCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthCheckerClient) IcmpCheck(ctx context.Context, in *IcmpCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/healthcheck.HealthChecker/IcmpCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthCheckerClient) TcpCheck(ctx context.Context, in *TcpCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/healthcheck.HealthChecker/TcpCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthCheckerServer is the server API for HealthChecker service.
// All implementations must embed UnimplementedHealthCheckerServer
// for forward compatibility
type HealthCheckerServer interface {
	//HTTP(S) health check
	HttpCheck(context.Context, *HttpCheckRequest) (*HealthCheckResponse, error)
	//ICMP health check
	IcmpCheck(context.Context, *IcmpCheckRequest) (*HealthCheckResponse, error)
	//TCP health check
	TcpCheck(context.Context, *TcpCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedHealthCheckerServer()
}

// UnimplementedHealthCheckerServer must be embedded to have forward compatible implementations.
type UnimplementedHealthCheckerServer struct {
}

func (UnimplementedHealthCheckerServer) HttpCheck(context.Context, *HttpCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HttpCheck not implemented")
}
func (UnimplementedHealthCheckerServer) IcmpCheck(context.Context, *IcmpCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IcmpCheck not implemented")
}
func (UnimplementedHealthCheckerServer) TcpCheck(context.Context, *TcpCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TcpCheck not implemented")
}
func (UnimplementedHealthCheckerServer) mustEmbedUnimplementedHealthCheckerServer() {}

// UnsafeHealthCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthCheckerServer will
// result in compilation errors.
type UnsafeHealthCheckerServer interface {
	mustEmbedUnimplementedHealthCheckerServer()
}

func RegisterHealthCheckerServer(s grpc.ServiceRegistrar, srv HealthCheckerServer) {
	s.RegisterService(&HealthChecker_ServiceDesc, srv)
}

func _HealthChecker_HttpCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckerServer).HttpCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/healthcheck.HealthChecker/HttpCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckerServer).HttpCheck(ctx, req.(*HttpCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthChecker_IcmpCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IcmpCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckerServer).IcmpCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/healthcheck.HealthChecker/IcmpCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckerServer).IcmpCheck(ctx, req.(*IcmpCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthChecker_TcpCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TcpCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthCheckerServer).TcpCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/healthcheck.HealthChecker/TcpCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthCheckerServer).TcpCheck(ctx, req.(*TcpCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthChecker_ServiceDesc is the grpc.ServiceDesc for HealthChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "healthcheck.HealthChecker",
	HandlerType: (*HealthCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HttpCheck",
			Handler:    _HealthChecker_HttpCheck_Handler,
		},
		{
			MethodName: "IcmpCheck",
			Handler:    _HealthChecker_IcmpCheck_Handler,
		},
		{
			MethodName: "TcpCheck",
			Handler:    _HealthChecker_TcpCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "healthcheck/api.proto",
}
